<?php

declare(strict_types=1);

namespace Carve\Generators;

final class ServiceGenerator
{
    public function __construct(
        private readonly StubRenderer $renderer,
        private readonly FileWriter $writer,
        private readonly GenerationManifest $manifest,
    ) {}

    public function generate(
        string $boundary,
        string $boundariesPath,
        string $runtime = 'laravel',
        string $outputDir = 'carve-output/services',
        array $options = [],
    ): array {
        $boundaryData = $this->loadBoundaryData($boundary, $boundariesPath);

        $targetDir = "{$outputDir}/{$boundary}";
        $files = [];

        $files[] = $this->writeServiceFile($targetDir, 'README.md', $this->renderer->render('service-skeleton/README.md.stub', [
            'SERVICE_NAME' => $boundaryData['name'] ?? $boundary,
            'CARVE_VERSION' => '0.1.0',
            'ROUTES_LIST' => implode("\n", array_map(fn ($r) => "- {$r}", $boundaryData['routes'] ?? [])),
        ]));

        $files[] = $this->writeServiceFile($targetDir, 'composer.json', json_encode([
            'name' => "carve/{$boundary}",
            'description' => "{$boundary} service generated by CarvePHP",
            'type' => 'project',
            'require' => [
                'php' => '^8.2',
                'laravel/framework' => '^11.0',
            ],
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $files[] = $this->writeServiceFile($targetDir, '.env.example', "APP_NAME={$boundary}\nAPP_ENV=local\n");
        $files[] = $this->writeServiceFile($targetDir, 'routes/api.php', "<?php\n\n// TODO: Define {$boundary} API routes\n");

        $totalFiles = $this->manifest->generate($boundary, $files, [
            'warnings' => [
                'Controller migration is generated as placeholder because method body adaptation is not safe in v0.1.',
            ],
            'next_steps' => [
                'Review generated service structure',
                'Copy monolith client into app/Clients',
                'Enable feature flag in staging',
                'Run generated contract tests',
            ],
        ]);

        return $totalFiles;
    }

    private function loadBoundaryData(string $boundary, string $path): array
    {
        if (! file_exists($path)) {
            return ['name' => $boundary, 'routes' => []];
        }

        $data = json_decode(file_get_contents($path), true) ?? [];

        foreach ($data['candidates'] ?? [] as $candidate) {
            if (($candidate['slug'] ?? '') === $boundary) {
                return $candidate;
            }
        }

        return ['name' => $boundary, 'routes' => []];
    }

    private function writeServiceFile(string $targetDir, string $relativePath, string $content): array
    {
        $fullPath = "{$targetDir}/{$relativePath}";

        $this->writer->write($fullPath, $content, mkdir: true);

        return [
            'path' => $relativePath,
            'type' => 'service_file',
            'status' => 'created',
        ];
    }
}
