<?php

declare(strict_types=1);

namespace Carve\Reports;

final class MarkdownReportWriter
{
    public function generate(?string $scanPath, ?string $graphPath, ?string $boundariesPath): string
    {
        $scanData = $this->loadJson($scanPath);
        $graphData = $this->loadJson($graphPath);
        $boundariesData = $this->loadJson($boundariesPath);

        $lines = [];
        $lines[] = '# CarvePHP Migration Report';
        $lines[] = '';
        $lines[] = 'Generated: '.date('c');
        $lines[] = '';
        $lines[] = $this->executiveSummary($scanData, $graphData, $boundariesData);
        $lines[] = $this->applicationOverview($scanData);
        $lines[] = $this->routeToTableMap($scanData);
        $lines[] = $this->runtimeHotspots($graphData);
        $lines[] = $this->candidateBoundaries($boundariesData);
        $lines[] = $this->sharedTablesAndCrossBoundaryWrites($graphData, $boundariesData);
        $lines[] = $this->recommendedMvpExtractionOrder($boundariesData);
        $lines[] = $this->limitationsAndWarnings();
        $lines[] = $this->nextSteps();

        return implode("\n", $lines);
    }

    private function executiveSummary(?array $scan, ?array $graph, ?array $boundaries): string
    {
        $routeCount = count($scan['routes'] ?? []);
        $classCount = count($scan['classes'] ?? []);
        $modelCount = count($scan['models'] ?? []);
        $tableCount = count($scan['tables'] ?? []);
        $nodeCount = $graph['nodes'] ?? [];
        $edgeCount = $graph['edges'] ?? [];
        $candidateCount = count($boundaries['candidates'] ?? []);

        $lines = [];
        $lines[] = '## Executive Summary';
        $lines[] = '';
        $lines[] = 'This report was generated by CarvePHP, a Laravel-first toolkit that combines static analysis and runtime tracing to identify service boundaries in monolith applications.';
        $lines[] = '';

        $lines[] = '| Metric | Value |';
        $lines[] = '|--------|-------|';
        $lines[] = '| Routes | '.$routeCount.' |';
        $lines[] = '| Controllers / Classes | '.$classCount.' |';
        $lines[] = '| Eloquent Models | '.$modelCount.' |';
        $lines[] = '| Database Tables | '.$tableCount.' |';
        $lines[] = '| Graph Nodes | '.count($nodeCount).' |';
        $lines[] = '| Graph Edges | '.count($edgeCount).' |';
        $lines[] = '| Candidate Boundaries | '.$candidateCount.' |';
        $lines[] = '';

        if ($candidateCount > 0) {
            $lines[] = '### Discovered Candidates';
            $lines[] = '';
            foreach ($boundaries['candidates'] ?? [] as $c) {
                $lines[] = "- **{$c['name']}** — Confidence: ".number_format($c['confidence'] * 100, 1).'%, Risk: '.number_format($c['risk_score'] * 100, 1).'%';
            }
            $lines[] = '';
        }

        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function applicationOverview(?array $scan): string
    {
        $lines = [];
        $lines[] = '## Application Overview';
        $lines[] = '';
        $lines[] = '### Routes';
        $lines[] = '';
        $lines[] = '| Method | URI | Name | Controller |';
        $lines[] = '|--------|-----|------|------------|';

        foreach ($scan['routes'] ?? [] as $route) {
            $lines[] = '| '.($route['method'] ?? '').' | '.($route['uri'] ?? '').' | '.($route['name'] ?? '').' | '.($route['controller'] ?? 'Closure').' |';
        }

        $lines[] = '';
        $lines[] = '### Models';
        $lines[] = '';
        $lines[] = '| Class | Table | Relationships |';
        $lines[] = '|-------|-------|---------------|';

        foreach ($scan['models'] ?? [] as $model) {
            $rels = implode(', ', $model['relationships'] ?? []);
            $lines[] = '| '.$model['class'].' | '.($model['table'] ?? '').' | '.$rels.' |';
        }

        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function routeToTableMap(?array $scan): string
    {
        $lines = [];
        $lines[] = '## Route to Table Map';
        $lines[] = '';
        $lines[] = 'The following map shows which database tables each route touches, derived from controller dependencies and raw SQL detection.';
        $lines[] = '';

        // Build controller -> tables map from db_usages
        $fileControllerMap = [];
        foreach ($scan['classes'] ?? [] as $class) {
            if (isset($class['file'])) {
                $shortName = $class['name'];
                $fileControllerMap[$class['file']] = $shortName;
            }
        }

        $controllerTables = [];
        foreach ($scan['db_usages'] ?? [] as $usage) {
            $ctrlName = $fileControllerMap[$usage['file'] ?? ''] ?? null;
            if ($ctrlName !== null) {
                $controllerTables[$ctrlName] = array_unique(array_merge(
                    $controllerTables[$ctrlName] ?? [],
                    $usage['raw_sql_tables'] ?? [],
                ));
            }
        }

        $lines[] = '| Route | Controller | Tables |';
        $lines[] = '|-------|------------|--------|';

        foreach ($scan['routes'] ?? [] as $route) {
            $ctrlName = $route['controller'] ?? '';
            $tables = $controllerTables[$ctrlName] ?? [];
            $tableStr = ! empty($tables) ? '`'.implode('`, `', $tables).'`' : '—';
            $lines[] = '| '.($route['method'] ?? '').' '.($route['uri'] ?? '').' | '.$ctrlName.' | '.$tableStr.' |';
        }

        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function runtimeHotspots(?array $graph): string
    {
        $lines = [];
        $lines[] = '## Runtime Hotspots';
        $lines[] = '';
        $lines[] = 'Areas with high edge density indicate strong coupling at runtime.';
        $lines[] = '';

        if ($graph === null || empty($graph['edges'])) {
            $lines[] = '_No graph data available. Run carve:analyze with runtime traces enabled._';
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';

            return implode("\n", $lines);
        }

        // Find tables with highest edge weight (most coupled)
        $tableWeights = [];
        foreach ($graph['edges'] ?? [] as $edge) {
            if (str_starts_with($edge['to'], 'table:') || str_starts_with($edge['from'], 'table:')) {
                $tableId = str_replace('table:', '', str_starts_with($edge['to'], 'table:') ? $edge['to'] : $edge['from']);
                $otherId = str_replace('table:', '', str_starts_with($edge['to'], 'table:') ? $edge['from'] : $edge['to']);
                $tableWeights[$tableId][] = ['connected_to' => $otherId, 'weight' => $edge['weight'], 'type' => $edge['type']];
            }
        }

        if (! empty($tableWeights)) {
            $lines[] = '### Table Connectivity';
            $lines[] = '';
            $lines[] = '| Table | Connections | Total Weight |';
            $lines[] = '|-------|-------------|--------------|';

            foreach ($tableWeights as $table => $connections) {
                $totalWeight = array_sum(array_column($connections, 'weight'));
                $lines[] = '| `'.$table.'` | '.count($connections).' | '.number_format($totalWeight, 1).' |';
            }
            $lines[] = '';
        }

        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function candidateBoundaries(?array $boundaries): string
    {
        $lines = [];
        $lines[] = '## Candidate Boundaries';
        $lines[] = '';

        $candidates = $boundaries['candidates'] ?? [];

        if (empty($candidates)) {
            $lines[] = '_No candidates found. Adjust algorithm parameters or ensure graph data exists._';
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';

            return implode("\n", $lines);
        }

        foreach ($candidates as $i => $candidate) {
            $lines[] = '### '.($i + 1).'. '.$candidate['name'];
            $lines[] = '';
            $lines[] = '| Metric | Value |';
            $lines[] = '|--------|-------|';
            $lines[] = '| Confidence | '.number_format($candidate['confidence'] * 100, 1).'% |';
            $lines[] = '| Cohesion Score | '.number_format($candidate['cohesion_score'] * 100, 1).'% |';
            $lines[] = '| Coupling Score | '.number_format($candidate['coupling_score'] * 100, 1).'% |';
            $lines[] = '| Risk Score | '.number_format($candidate['risk_score'] * 100, 1).'% |';
            $lines[] = '';

            if (! empty($candidate['tables'])) {
                $lines[] = '**Tables:** '.implode(', ', array_map(fn ($t) => "`{$t}`", $candidate['tables']));
                $lines[] = '';
            }
            if (! empty($candidate['controllers'])) {
                $lines[] = '**Controllers:** '.implode(', ', array_map(fn ($c) => "`{$c}`", $candidate['controllers']));
                $lines[] = '';
            }
            if (! empty($candidate['routes'])) {
                $lines[] = '**Routes:**';
                foreach ($candidate['routes'] as $r) {
                    $lines[] = "- `{$r}`";
                }
                $lines[] = '';
            }
            if (! empty($candidate['models'])) {
                $lines[] = '**Models:** '.implode(', ', array_map(fn ($m) => "`{$m}`", $candidate['models']));
                $lines[] = '';
            }
            if (! empty($candidate['explanation'])) {
                $lines[] = '**Why suggested:**';
                foreach ($candidate['explanation'] as $exp) {
                    $lines[] = "- {$exp}";
                }
                $lines[] = '';
            }
            if (! empty($candidate['warnings'])) {
                $lines[] = '**Warnings:**';
                foreach ($candidate['warnings'] as $w) {
                    $lines[] = "- ⚠ {$w}";
                }
                $lines[] = '';
            }
        }

        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function sharedTablesAndCrossBoundaryWrites(?array $graph, ?array $boundaries): string
    {
        $lines = [];
        $lines[] = '## Shared Tables and Cross-Boundary Writes';
        $lines[] = '';

        $candidates = $boundaries['candidates'] ?? [];

        if (empty($candidates) || $graph === null) {
            $lines[] = '_Data insufficient for cross-boundary write analysis._';
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';

            return implode("\n", $lines);
        }

        // Find tables appearing in multiple candidates
        $tableCandidateMap = [];
        foreach ($candidates as $c) {
            foreach ($c['tables'] ?? [] as $table) {
                $tableCandidateMap[$table][] = $c['name'];
            }
        }

        $sharedTables = array_filter($tableCandidateMap, fn ($cands) => count($cands) > 1);

        if (! empty($sharedTables)) {
            $lines[] = '| Table | Shared By |';
            $lines[] = '|-------|-----------|';
            foreach ($sharedTables as $table => $cands) {
                $lines[] = '| `'.$table.'` | '.implode(', ', $cands).' |';
            }
            $lines[] = '';
            $lines[] = '> ⚠ Shared tables indicate coupling. Consider splitting or creating shared kernel tables during extraction.';
        } else {
            $lines[] = '_No tables are shared across candidate boundaries._';
        }

        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function recommendedMvpExtractionOrder(?array $boundaries): string
    {
        $lines = [];
        $lines[] = '## Recommended MVP Extraction Order';
        $lines[] = '';

        $candidates = $boundaries['candidates'] ?? [];

        if (empty($candidates)) {
            $lines[] = '_No candidates to rank._';
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';

            return implode("\n", $lines);
        }

        // Sort by risk score ascending (lowest risk first)
        $sorted = $candidates;
        usort($sorted, fn ($a, $b) => $a['risk_score'] <=> $b['risk_score']);

        $lines[] = '| Priority | Boundary | Confidence | Risk | Rationale |';
        $lines[] = '|----------|----------|------------|------|-----------|';
        foreach ($sorted as $i => $c) {
            $rationale = $c['risk_score'] < 0.3
                ? 'Low risk — good first extraction candidate'
                : ($c['risk_score'] < 0.6
                    ? 'Moderate risk — review shared dependencies'
                    : 'High risk — requires careful planning');
            $lines[] = '| '.($i + 1).' | '.$c['name'].' | '.number_format($c['confidence'] * 100, 1).'% | '.number_format($c['risk_score'] * 100, 1).'% | '.$rationale.' |';
        }

        $lines[] = '';
        $lines[] = '> **Recommendation:** Start with the boundary that has the highest confidence and lowest risk. This minimizes disruption and proves the extraction pattern before tackling more complex boundaries.';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function limitationsAndWarnings(): string
    {
        $lines = [];
        $lines[] = '## Limitations and Warnings';
        $lines[] = '';
        $lines[] = '- This report is based on **automated analysis** and requires **human review** before any architectural decisions.';
        $lines[] = '- Boundary suggestions are **statistical** and may not reflect actual domain boundaries defined by business requirements.';
        $lines[] = '- Runtime tracing must be enabled and have sufficient traffic data to improve accuracy.';
        $lines[] = '- Static analysis cannot detect dynamic table names, raw SQL with string interpolation, or runtime-only behaviors.';
        $lines[] = '- The graph represents observed relationships only; missing edges do not guarantee independence.';
        $lines[] = '- Shared tables across boundaries require careful migration strategies (e.g., view tables, event-based sync).';
        $lines[] = '- Extraction order is a suggestion; actual priority should consider team ownership, business value, and technical debt.';
        $lines[] = '- CarvePHP does **not** modify your application files or automatically extract microservices.';

        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function nextSteps(): string
    {
        $lines = [];
        $lines[] = '## Generated Commands / Next Steps';
        $lines[] = '';
        $lines[] = '```bash';
        $lines[] = '# 1. Re-scan after making code changes';
        $lines[] = 'php artisan carve:scan --pretty';
        $lines[] = '';
        $lines[] = '# 2. Rebuild the graph with runtime traces';
        $lines[] = 'php artisan carve:analyze';
        $lines[] = '';
        $lines[] = '# 3. Re-run boundary detection';
        $lines[] = 'php artisan carve:boundaries --report=carve-boundaries.md';
        $lines[] = '';
        $lines[] = '# 4. Compare with previous run';
        $lines[] = '# php artisan carve:diff --before=carve-report-1.md --after=carve-report-2.md';
        $lines[] = '```';
        $lines[] = '';
        $lines[] = '### Enable Runtime Tracing for Better Results';
        $lines[] = '';
        $lines[] = '```bash';
        $lines[] = 'php artisan carve:trace-install';
        $lines[] = 'echo "CARVE_TRACE_ENABLED=true" >> .env';
        $lines[] = 'php artisan migrate';
        $lines[] = '```';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';
        $lines[] = '> _Generated by [CarvePHP](https://github.com/Muhammad-Waleed-Khalil/CarvePHP) — Find service boundaries in Laravel monoliths using static analysis + runtime tracing._';

        return implode("\n", $lines);
    }

    private function loadJson(?string $path): ?array
    {
        if ($path === null || ! file_exists($path)) {
            return null;
        }

        return json_decode(file_get_contents($path), true);
    }
}
